apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: singress
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: read-secrets-global
subjects:
- kind: ServiceAccount
  name: singress
  namespace: linode
roleRef:
  kind: ClusterRole
  name: singress
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: singress
  namespace: linode
---
apiVersion: v1
kind: Service
metadata:
  name: singress
  namespace: linode
spec:
  type: ClusterIP
  selector:
    app: singress
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: singress
  namespace: linode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: singress
  template:
    metadata:
      labels:
        app: singress
    spec:
      containers:
      - image: ghcr.io/andyleap-cluster/singress@sha256:02882225530ecf0770e013e782e58d6a3bbdbbd3299575297517b28e69c8a073
        name: singress
        env:
        - name: S3_DOMAIN
          value: us-sea-1.linodeobjects.com
        - name: S3_BUCKET
          value: andyleap-dev-tls
        - name: S3_KEY
          valueFrom:
            secretKeyRef:
              name: singress-api-token
              key: key
        - name: S3_SECRET
          valueFrom:
            secretKeyRef:
              name: singress-api-token
              key: secret
        ports:
          - containerPort: 80
            name: http
          - containerPort: 443
            name: https
      serviceAccountName: singress
