apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
# Using ArgoCD upstream Kustomize base - pinned to v3.1.1
- https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.1/manifests/install.yaml
- certificate.yaml
- httproute.yaml
- referencegrant.yaml

configMapGenerator:
- name: argocd-cmd-params-cm
  behavior: merge
  literals:
  - server.insecure=true
